### ISSUE TITLE
ASCOM 7 RC4, Install problem, sees old developer tools and can not uninstall it

### ISSUE THREAD

**Issue by han-k59** [ASCOMInitiative/ASCOMPlatform#72] opened 2024-08-02 12:09 UTC
Can not install Ascom7, RC4. See screenshot.  Developer tools are NOT installed. Anything in registry I could remove?

Han

![ascom7 Untitled](https://github.com/user-attachments/assets/e4e7c928-53c1-4f81-a935-315077b1d753)

**Comment by han-k59** [comment] 2024-08-02 12:20
I can install the following ASCOM versions
6.4,
6.61,
6.6.2beta.3677
6.6.2.4294

but not 
7RC1
7RC4

**Comment by han-k59** [comment] 2024-08-02 12:35
The commandline option does not help either:
   /removeascom command line parameter

**Comment by Peter-Simpson** [comment] 2024-08-02 13:51
Hi Han,

The issue is that the Platform 6 Developer Tools application is recorded as being installed on your PC but its uninstall program is missing or not working for some reason. From my experience, the application can no longer be uninstalled automatically when this happens.

The Platform 7 installer provides all the files that were present in the Platform 6 Developer Tools so I am building a revised installer that will quietly remove the developer tools install record when the application can't be uninstalled. This should allow the install to proceed normally for you.

I'll post a link to the new installer in a couple of hours when its built and tested.

Best wishes, Peter

**Comment by Peter-Simpson** [comment] 2024-08-02 16:09
Hi Han,

Here is a revised installer that should fix the issue you saw: [AscomPlatform700.rc4.4449](https://download.ascom-standards.org/beta/platform7/AscomPlatform700.rc4.4449.exe)

Best wishes, Peter

**Comment by Peter-Simpson** [comment] 2024-08-03 11:48
Please can you confirm whether this has fixed the issue.

Best wishes, Peter

**Comment by han-k59** [comment] 2024-08-03 12:35
Yes this version installs fine. Thanks.

Sorry I could not respond earlier. 

Cheers, Han

**Comment by Peter-Simpson** [comment] 2024-08-06 07:36
Thanks Han, closing this as fixed.

best wishes, Peter

**Closed by Peter-Simpson** 2024-08-06 07:36 UTC
